version: '3.8'

services:
  mcp:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: mcp
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data
      - ./server:/app
    environment:
      - TARGET_DIR=/data
      - PORT=3000
      - API_KEY=${API_KEY:-your-secret-api-key-here}
    networks:
      - mcp-network

  mcp-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: mcp-client
    depends_on:
      - mcp
    volumes:
      - ./client:/app
    environment:
      - SERVER_URL=ws://mcp:3000
      - API_KEY=${API_KEY:-your-secret-api-key-here}
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge
